# Generated by Django 3.2.9 on 2021-11-28 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_image_images'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='Image',
        ),
    ]
