# Generated by Django 3.2.9 on 2021-11-28 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_image_small_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='small_img',
            field=models.ImageField(blank=True, null=True, upload_to='small_img'),
        ),
    ]
