# Generated by Django 3.2.9 on 2021-11-28 07:53

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_image_small_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='small_img',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=0, size=[1920, 1080], upload_to='small_img'),
        ),
    ]
