# Generated by Django 3.2.9 on 2021-11-29 18:14

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20211129_0313'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilepic',
            name='bio',
            field=models.CharField(default='Hey there, I am using Kliks.', max_length=100),
        ),
        migrations.AlterField(
            model_name='image',
            name='small_img',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=80, size=[1024, 768], upload_to='small_img'),
        ),
    ]
